### ISSUE TITLE
resnext 50 on imagenet load pretrain model failed

### ISSUE THREAD

**Issue by yaoing** [bearpaw/pytorch-classification#18]
i try to modify resnext50 function to:
```
def resnext50(baseWidth, cardinality,pretrained=True):
    """
    Construct ResNeXt-50.
    """
    model = ResNeXt(baseWidth, cardinality, [3, 4, 6, 3], 1000)
    if pretrained:
        model.load_state_dict(torch.load('model_best.pth.tar')['state_dict'])
        print('loaded model')

    return model
```
the model_best.pth.tar file download from the link of readme.md

and some errors raised when i run:
```
Traceback (most recent call last):
  File "imagenet.py", line 348, in <module>
    main()
  File "imagenet.py", line 152, in main
    cardinality=args.cardinality,
  File "/media/amax/xgessd/yao/pytorch-classification/models/imagenet/resnext.py", line 160, in resnext50
    model.load_state_dict(torch.load('ResNext50_checkpoint_best.pth.tar')['state_dict'])
  File "/home/amax/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNeXt:
	Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias", "bn1.running_mean", "bn1.running_var", "lay........
```

**Comment by yaoing** [comment]
求助~

**Comment by bearpaw** [comment]
Please refer to the `--resume` parameter about loading a pretrained model:
https://github.com/bearpaw/pytorch-classification/blob/master/imagenet.py#L171-L181

**Comment by yaoing** [comment]
@bearpaw OK,I solved !

**Comment by yaoing** [comment]
但是其他地方还有个小问题 , 比如 跑resnext 好像默认只支持单卡的,我做了微调之后才解决了

再次表示感谢~
